### ISSUE TITLE
Add ability to assume units not located in base zones once on mission start

### ISSUE THREAD

**Issue by birgersp** [birgersp/dcs-autogft#59]
`addInitialUnitsZone`

**Comment by thebgpikester** [comment]
Was thinking to scan the units on both sides at start and check for a prefix like __XXX__ that wouldnt be accidentally there. All those groups would then be IGNORED, the remaining groups would be "Seized" control of.
Discussion: How to set skill, speed, objectives to units that do not have one. Do we set a default set of characteristics for all discovered groups? So non Task force units will exist....

**Comment by thebgpikester** [comment]
Above question already asked under #57

**Comment by birgersp** [comment]
(As we've discussed) The alternative is look for groups of units with a prefix like **TF** and then assume control of those units. Which would you prefer?

**Comment by thebgpikester** [comment]
Hmm, Theres conflicting benefits, common sense says that you should manually include objects you want controlled. Ease of use says you should manually exclude ones you dont want to control. I'm erring to the former, it also makes sense because if we have persistence that issue says we need to manually name groups, so the manual part will have to be an active choice which forces the designer to consider things better, rather than encourage the opposite. Any other reasons you can think of?

**Comment by birgersp** [comment]
Issue descirption:

>For missions with larger distance between base zones and target zones, units will spend a lot of time to travel to their objective. Mission designers may want task force units to initially be located closer to their objective on mission start.

- Add function to task force which assumes control of any unit in the mission with a group name beginning with "TF".
- If the group name beginning with "TF" has a third letter which is a number N, reserve this group for the N-th created task force
